name: vlib-enumerate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.3
  - pandas=1.5.3
  - pillow=9.4.0
  - psycopg2=2.9.3
  - pydantic=1.10.2
  - rdkit=2022.09.5
  - tqdm=4.65.0
  - hydra-core=1.3
